apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-reducedsubs-oct24
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-reducedsubs-oct24 
  name: test-reducedsubs-oct24
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-reducedsubs-oct24 
